version: '3'
services:
  influxdb:
    image: influxdb:2.2.0
    container_name: influxdb
    env_file:
      - ./.env
    ports:
      - '8086:8086'
    volumes:
      - influxdb_data-storage:/var/lib/influxdb2:rw
      - influxdb_config-storage:/etc/influxdb2:rw
      - ./influxdb.json:/etc/influxdb2/config.json:rw
      - ./influx-configs:/etc/influxdb2/influx-configs:rw
      - ./influxdb-selfsigned.key:/etc/ssl/influxdb-selfsigned.key:ro
      - ./influxdb-selfsigned.crt:/etc/ssl/influxdb-selfsigned.crt:ro
    environment:
      # - INFLUXDB_DATA_CACHE_MAX_MEMORY_SIZE=100000000
      # - INFLUXD_QUERY_INITIAL_MEMORY_BYTES=5485760
      # - INFLUXD_QUERY_MAX_MEMORY_BYTES=54857600
      # - INFLUXD_QUERY_MEMORY_BYTES=5485760
      # - INFLUXD_STORAGE_CACHE_MAX_MEMORY_SIZE=573741824
      # - INFLUXD_STORAGE_CACHE_SNAPSHOT_MEMORY_SIZE=26214400
      - INFLUXDB_DB=${INFLUXDB_DB}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_NAME}
      - INFLUXDB_ADMIN_PASSWORD="${INFLUXDB_ADMIN_PASSWORD}"
      - INFLUXDB_USER=${INFLUXDB_USER_NAME}
      - INFLUXDB_USER_PASSWORD=${INFLUXDB_USER_PASSWORD}
  grafana:
    image: grafana/grafana:8.1.1
    container_name: grafana
    ports:
      - '3000:3000'
    volumes:
      - docker-compose-influxdb-grafana_grafana-storage:/var/lib/grafana
      - ./grafana-provisioning/:/etc/grafana/provisioning
      - ./influxdb-selfsigned.key:/etc/ssl/private/influxdb-selfsigned.key:rw
      - ./influxdb-selfsigned.crt:/etc/ssl/certs/influxdb-selfsigned.crt:ro
      - ./grafana.ini:/etc/grafana/grafana.ini:ro
    depends_on:
      - influxdb
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    restart: always
volumes:
  docker-compose-influxdb-grafana_grafana-storage:
          external: true
  influxdb_data-storage:
  influxdb_config-storage:

